In [26]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
import joblib

In [2]:
df=pd.read_excel("calorie_dataset.xlsx")
df

Sl_no  Gender  Age  Height  Weight        Activity Intensity  Duration  \
0         1  Female   30     159      59   Outdoor Games  Moderate      29.0   
1         2    Male   38     171      75         Walking     Light       2.0   
2         3    Male   20     183      88         Running  Moderate      16.0   
3         4  Female   25     160      59         Cycling  Moderate      24.0   
4         5  Female   24     165      59         Running  Moderate      18.0   
...     ...     ...  ...     ...     ...             ...       ...       ...   
1115   1116    Male   23     181      85   Outdoor Games  Moderate      19.0   
1116   1117    Male   68     185      87         Walking  Moderate      10.0   
1117   1118  Female   57     160      67  Weight_lifting  Moderate      27.0   
1118   1119    Male   40     182      86  Weight_lifting  Moderate       7.0   
1119   1120    Male   22     177      80        Swimming     Light       7.0   

      Heart_Rate  Calories  
0          106.0       195  
1           81.0         5  
2           97.0        69  
3          102.0       136  
4           91.0        80  
...          ...       ...  
1115        93.0        72  
1116       101.0        72  
1117       109.0       185  
1118        93.0        32  
1119        86.0        18  

[1120 rows x 10 columns]

In [3]:
df.isnull().sum()

Sl_no         0
Gender        0
Age           0
Height        0
Weight        0
Activity      0
Intensity     0
Duration      8
Heart_Rate    6
Calories      0
dtype: int64

In [4]:
df["Gender"].value_counts()

Female    570
Male      550
Name: Gender, dtype: int64

In [5]:
df["Activity"].value_counts()

Swimming                 227
Weight_lifting           188
Running                  184
Cycling                  168
Cardio_gym_activities    120
Walking                  118
Outdoor Games            115
Name: Activity, dtype: int64

In [6]:
df['Intensity'].value_counts()

Moderate    678
Light       376
Heavy        66
Name: Intensity, dtype: int64

In [7]:
df1=df.copy()
df1

Sl_no  Gender  Age  Height  Weight        Activity Intensity  Duration  \
0         1  Female   30     159      59   Outdoor Games  Moderate      29.0   
1         2    Male   38     171      75         Walking     Light       2.0   
2         3    Male   20     183      88         Running  Moderate      16.0   
3         4  Female   25     160      59         Cycling  Moderate      24.0   
4         5  Female   24     165      59         Running  Moderate      18.0   
...     ...     ...  ...     ...     ...             ...       ...       ...   
1115   1116    Male   23     181      85   Outdoor Games  Moderate      19.0   
1116   1117    Male   68     185      87         Walking  Moderate      10.0   
1117   1118  Female   57     160      67  Weight_lifting  Moderate      27.0   
1118   1119    Male   40     182      86  Weight_lifting  Moderate       7.0   
1119   1120    Male   22     177      80        Swimming     Light       7.0   

      Heart_Rate  Calories  
0          106.0       195  
1           81.0         5  
2           97.0        69  
3          102.0       136  
4           91.0        80  
...          ...       ...  
1115        93.0        72  
1116       101.0        72  
1117       109.0       185  
1118        93.0        32  
1119        86.0        18  

[1120 rows x 10 columns]

In [8]:
le=LabelEncoder()
df1["Gender"]=le.fit_transform(df1["Gender"])
df1['Activity']=le.fit_transform(df1["Activity"])

In [9]:
inten_map={"Light":0,"Moderate":1,"Heavy":2}
df1["Intensity"]=df1["Intensity"].map(lambda x: inten_map.get(x))

In [10]:
dur_mean=df1["Duration"].mean()
dur_mean

15.568345323741006

In [11]:
heart_mean=df1["Heart_Rate"].mean()
heart_mean

95.46319569120287

In [12]:
df1=df1.fillna({"Duration":int(dur_mean),"Heart_Rate":int(heart_mean)})

In [13]:
df1.isnull().sum()

Sl_no         0
Gender        0
Age           0
Height        0
Weight        0
Activity      0
Intensity     0
Duration      0
Heart_Rate    0
Calories      0
dtype: int64

In [14]:
x=df1.drop(["Sl_no","Heart_Rate","Calories"],axis=1)
y=df1["Calories"]

In [15]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.2,random_state=42)

In [16]:
model=LinearRegression()
model.fit(x_train,y_train)
model.score(x_test,y_test)

0.9306519046552711

In [17]:
#Gender::::female-0,male-1
#Activity::::Outdoor Games-0 
#             Running      -1
#             Walking      -2
#             cardi-gym-activities -3
#             Cycling      -4
#             swimming      -5
#             weight lifting-6 
# Intensity::::::light  -0
#                moderate -1
#                heavy  -2

In [18]:
# enter gender,Age,Height,Weight,Activity,Intensity,Duration in minute
model.predict([[1,26,159,48,3,1,15]])

C:\Users\deept\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([79.88874835])

In [23]:
pickle.dump(model,open('calorie_model.ipynb','wb'))

In [24]:
model1=pickle.load(open('calorie_model.ipynb','rb'))


In [25]:
model1.predict([[1,26,159,48,3,1,15]])

C:\Users\deept\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([79.88874835])

In [28]:
joblib.dump(model,"lin_model")

['lin_model']

In [31]:
model2=joblib.load("lin_model")

In [32]:
model2.predict([[1,26,159,48,3,1,15]])

C:\Users\deept\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([79.88874835])